apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'frontend'
  labels:
    app: 'frontend'
spec:
  selector:
    matchLabels:
      app: 'frontend'
  replicas: 10
  template:
    metadata:
      name: 'frontend'
      labels:
        app: 'frontend'
    spec:
      containers:
        - name: 'express'
          image: helioalb/k8s-example:v2
